//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (VSTO).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickameOutlookAssistant
{
    /// <summary>
    /// VSTO generated code.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.CodeGeneration",
        "10.0.0.0")]
    public sealed partial class ThisAddIn : Microsoft.Office.Tools.Outlook.OutlookAddIn
    {
        internal Microsoft.Office.Tools.Outlook.Factory Factory;

        public ThisAddIn(global::Microsoft.Office.Tools.Outlook.Factory factory,
            global::System.IServiceProvider serviceProvider)
            : base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
            Globals.Factory = factory;
            this.Factory = factory;
        }

        /// <summary>
        /// Tipus fort de l'objecte Application d'Outlook.
        /// </summary>
        public new Microsoft.Office.Interop.Outlook.Application Application
        {
            get { return (Microsoft.Office.Interop.Outlook.Application)base.Application; }
        }

        protected override void Initialize()
        {
            base.Initialize();
            Globals.ThisAddIn = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InternalStartup();
        }
    }

    /// <summary>
    /// Accés global a l'add-in i a la factory de VSTO.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.CodeGeneration",
        "10.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static class Globals
    {
        private static ThisAddIn _ThisAddIn;
        private static global::Microsoft.Office.Tools.Outlook.Factory _factory;

        internal static ThisAddIn ThisAddIn
        {
            get { return _ThisAddIn; }
            set
            {
                if (_ThisAddIn != null)
                    throw new global::System.NotSupportedException();
                _ThisAddIn = value;
            }
        }

        internal static global::Microsoft.Office.Tools.Outlook.Factory Factory
        {
            get { return _factory; }
            set
            {
                if (_factory != null)
                    throw new global::System.NotSupportedException();
                _factory = value;
            }
        }
    }
}
